function Apistartup()
    shell.run("delete aapi_loader.lua")
    shell.run("pastebin get gWaWXz2q aapi_loader.lua")
    local loader = require("aapi_loader")
    loader.setVersion("m")
    loader.update()
    loader.core()
    loader.display()
    loader.audio()
    loader.custom("loaders/andysoftreactor_launcher.lua", "asr_launcher.lua")
    loader.custom("products/andysoftreactor.lua", "andysoftreactor.lua")
end
Apistartup()
shell.run("asr_launcher.lua")